name: PR Title Check
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  pr-title-check:
    runs-on: depot-ubuntu-22.04-2
    container:
      image: node:22
      credentials:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run PR title check
        run: |
          node .github/scripts/pr-title-check.js